services:
  race_stack:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        USER: race_crew
        UID: ${HOST_UID:-1000}
        GID: ${HOST_GID:-1000}
        IMAGE: ros:humble-desktop
    container_name: forzaeth_devcontainer
    image: race_stack:humble_dev
    network_mode: host
    ipc: host
    privileged: true
    shm_size: "1gb"
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    volumes:
      - /dev:/dev:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./:/ws/src/race_stack:rw
      - ../race_stack_cache/humble/build:/ws/build:rw
      - ../race_stack_cache/humble/install:/ws/install:rw
      - ../race_stack_cache/humble/log:/ws/log:rw
    environment:
      - DISPLAY=${DISPLAY}
      - USER=race_crew
      - USERNAME=race_crew
      - ROS_LOCALHOST_ONLY=0
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-48}
      - RCUTILS_COLORIZED_OUTPUT=1
      - TERM=xterm-256color
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - RACECAR_VERSION=${RACECAR_VERSION:-NUC1}
