
l1_param:
  t_clip_min:
    lower_bound: 0.1
    upper_bound: 0.2 # 1.0 to enforce bad laps for debugging
  m_l1:
    lower_bound: 0.05 
    upper_bound: 0.4
  q_l1:
    lower_bound: -1.0
    upper_bound: 1.0
sector:
  lower_bound: 0.8
  upper_bound: 1.0

