## L1 Controller Parameters (Lateral Control)
t_clip_min: 1
t_clip_max: 5
m_l1: 0.3
q_l1: 0.15
speed_lookahead: 0
lat_err_coeff: 1
acc_scaler_for_steer: 1.0
dec_scaler_for_steer: 1.0 
start_scale_speed: 7.0
end_scale_speed: 8.0
downscale_factor: 0.2
speed_lookahead_for_steer: 0 # safe/agg 0/0 # increasing this to 0.20 AT MOST can make the car faster on the laptime but cut more corners




## Trailing Controller Parameters
prioritize_dyn: True

trailing_gap: 1.5 # Distance in meters or gap in seconds, depending on mode
trailing_p_gain: 0.5
trailing_i_gain: 0.001
trailing_d_gain: 0.2
blind_trailing_speed: 1.5