# Parameters for local planner
rate: 40  # [hz]
test_on_car: True  # also set True if using on a bag
n_loc_wpnts: 50  # number of local waypoints published, 1 waypoints every 0.1 meter# TODO add s where we want to go aggressive
every_n_lap_aggressive: 3  # number of laps driven in aggressive mode

ftg_only: False 
ftg_mode: "aggressive"  # set to "safe" for precheck

# Parameters for follow the gap controller
debug: False  # publishes filtered scans if True but may not run smoothly

safety_radius: 40  # helps not to cut corners
bubble_radius: 45
preprocess_conv_size: 3
best_point_conv_size: 200  # helps not to cut corners
max_lidar_dist: 9.

range_offset: 220  # LiDAR has 1080 range points, only consider [range_offset,-range_offset]

# speed is scaled with (1 - (steering_angle/max_steering)**steering_punish) and min(1, gap_distance/track_width - gap_offset)
cont_approach: True  # continuous speed regulation
speed_filter: True
max_steering: 0.5
steering_punish: 2  # 0.4 for max_speed = 10, 0.75 for max_speed = 7
gap_offset: 0.1  # 0.1 or 0.05 for max_speed = 10, 0 for max_speed = 7
track_width: 2.6  # approx gap distance on a straight when there are no obstacles (set debug to True to see gap distances during driving)
max_speed: 6.
min_speed: 2.  
# not needed in ini version
speed_control_dist: 1.  # if distance to best point is smaller than this, then speed does also depend on this distance

# schedule for aggressivity
aggressive_schedule:
  - 0
  - 1
  - 0
  - 0
  - 1
  - 0
# parameter for switching
switch_position_s: 30
