speed_to_erpm_offset: 0.0
steering_angle_to_servo_gain: -1.2135
steering_angle_to_servo_offset: 0.55500
wheelbase: 0.3 # F1Tenth
invert_steering: false
speed_to_erpm_gain: 2401.79  # Wheel diameter: 0.11m (radius r = 0.055m)
                                # Speed (m/s) = r * ω (where r is the radius, ω is angular velocity)
                                # Angular velocity ω (rad/s) = (2 * pi / 60) * RPM
                                # Motor RPM = (60 / (2 * pi * r)) * speed (m/s)
                                # ERPM = Motor RPM * (Pole Count / 2)
                                # speed_to_erpm_gain considers gear ratio and motor pole count
