# Message definition for the Status field of https://s3.amazonaws.com/files.microstrain.com/CV7+Online/external_content/dcp/Data/sensor_data/data/mip_field_sensor_overrange_status.htm?Highlight=overrange
#   Note: This message will never be published on it's own, only included in other messages.

bool accel_x
bool accel_y
bool accel_z
bool gyro_x
bool gyro_y
bool gyro_z
bool mag_x
bool mag_y
bool mag_z
bool press